version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: hotel-backend/Dockerfile
    container_name: hotel-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - hotel-network

  frontend:
    build:
      context: .
      dockerfile: hotel-user/Dockerfile
    container_name: hotelUserApp
    ports:
      - "8081:8081"
    volumes:
      - ./hotel-user:/app
    networks:
      - hotel-network
    depends_on:
      - backend

networks:
  hotel-network:
    driver: bridge
