# Use the official Node.js image as a base
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to install dependencies
COPY hotel-backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code into the container
COPY hotel-backend/ .

# Expose the port the app will run on
EXPOSE 5000

# Command to run the app
CMD ["npm", "start"]
